### ISSUE TITLE
I Can't run terraform init

### ISSUE THREAD

**Issue by ridwanaliah** [TheSudoYT/terraform-aws-palworld#12]
the error said this:

Error: Failed to download module
│
│   on main.tf line 1:
│    1: module "palworld" {
│
│ Could not download module "palworld" (main.tf:1) source code from
│ "git::https://github.com/TheSudoYT/terraform-aws-palworld?ref=03668dc8fcd22be2ef78e3df0740e65e72537cb7":  
│ error downloading
│ 'https://github.com/TheSudoYT/terraform-aws-palworld?ref=03668dc8fcd22be2ef78e3df0740e65e72537cb7': git   
│ must be available and on the PATH.

can you help me how to fix this?

**Comment by ridwanaliah** [comment]
i fixed the issue, but i got terraform plan issue now:

it goes like this:
 Error: Invalid provider configuration
│
│ Provider "registry.terraform.io/hashicorp/aws" requires explicit configuration. Add a provider block to   
│ the root module and configure the provider's required arguments as described in the provider
│ documentation.
│
╵
╷
│ Error: No valid credential sources found
│
│   with provider["registry.terraform.io/hashicorp/aws"],
│   on <empty> line 0:
│   (source code not available)
│
│ Please see https://registry.terraform.io/providers/hashicorp/aws
│ for more information about providing credentials.
│
│ Error: failed to refresh cached credentials, no EC2 IMDS role found, operation error ec2imds:
│ GetMetadata, request canceled, context deadline exceeded

how to fixt this?

**Comment by Josh-Tracy** [comment]
> i fixed the issue, but i got terraform plan issue now:
> 
> it goes like this: Error: Invalid provider configuration │ │ Provider "registry.terraform.io/hashicorp/aws" requires explicit configuration. Add a provider block to │ the root module and configure the provider's required arguments as described in the provider │ documentation. │ ╵ ╷ │ Error: No valid credential sources found │ │ with provider["registry.terraform.io/hashicorp/aws"], │ on line 0: │ (source code not available) │ │ Please see https://registry.terraform.io/providers/hashicorp/aws │ for more information about providing credentials. │ │ Error: failed to refresh cached credentials, no EC2 IMDS role found, operation error ec2imds: │ GetMetadata, request canceled, context deadline exceeded
> 
> how to fixt this?

Did you configure your AWS credentials? Based on the error, it looks like terraform cannot find AWS credentials for the AWS provider.
