### ISSUE TITLE
Error: Failed to download module

### ISSUE THREAD

**Issue by Digginz88** [TheSudoYT/terraform-aws-palworld#2]
**What is your Question?**
I was trying to follow your youtube video and got to the terraform init part, but received an error.

"Failed to download module
│
│   on main.tf line 1:
│    1: module "palworld" {
│
│ Could not download module "palworld" (main.tf:1) source code from
│ "git::https://github.com/TheSudoYT/terraform-aws-palworld?ref=5e3223be6ab41a7b7189acccd6960ee2d8510dba": error downloading
│ 'https://github.com/TheSudoYT/terraform-aws-palworld?ref=5e3223be6ab41a7b7189acccd6960ee2d8510dba': git must be available and on the PATH."

Can you let me know what I'm doing wrong? Thanks for the in-depth guide!

![image](https://github.com/TheSudoYT/terraform-aws-palworld/assets/158023799/7eca8fab-3021-4c96-93c8-5cf21f4a8b00)

**Comment by Josh-Tracy** [comment]
Hi @Digginz88 ,

There are a few reasons this might happen.  First, can you expand  the .terraform folder and ensure the providers downloaded or not?

![image](https://github.com/TheSudoYT/terraform-aws-palworld/assets/55331456/a6f82bf2-7da3-426f-84a3-f3975951e58b)

Additionally, Can you provide some info?

- What OS are you running on
- How did you install Terraform on the OS?
- If you installed Terraform with a package manager, which one (snap, yum, apt, chocolatey, etc.)

**Comment by Digginz88** [comment]
Hi Josh!

The providers are not populated in the module. I must've missed a step?

![image](https://github.com/TheSudoYT/terraform-aws-palworld/assets/158023799/eb99b510-d28f-42bc-bb3d-fa27a0f2bcec)

* I'm using Windows
* I used the manual install process and set the Path in the Environment Variables section
* I can confirm that in the CMD Prompt, I have Terraform v1.7.1 installed and can run the help command.

Thanks!

**Comment by Josh-Tracy** [comment]
Thank you.  Do you have `git` installed on your PC? If not, can you install it, restart the terminal / cmd prompt, and try the terraform init again?

https://git-scm.com/book/en/v2/Getting-Started-Installing-Git

**Comment by Digginz88** [comment]
That did it - I was able to go through all the steps once I downloaded that. I really appreciate your help! This was fun to learn and your video made it very easy. 

Thank you!

**Comment by Josh-Tracy** [comment]
Glad to hear it!
